CREATE TABLE data_science.appstore_dataset (
  `app_id` VARCHAR(48),
  `app_name` VARCHAR(75),
  `appstore_url` VARCHAR(142),
  `primary_genre` VARCHAR(13),
  `content_rating` VARCHAR(3),
  `size_bytes` DOUBLE,
  `required_ios_version` DOUBLE,
  `released` VARCHAR(30),
  `updated` VARCHAR(30),
  `version` VARCHAR(7),
  `price` DOUBLE,
  `currency` VARCHAR(4),
  `free` DOUBLE,
  `developerid` DOUBLE,
  `developer` VARCHAR(39),
  `developer_url` VARCHAR(117),
  `developer_website` VARCHAR(255),
  `average_user_rating` DOUBLE,
  `reviews` DOUBLE,
  `current_version_score` DOUBLE,
  `current_version_reviews` DOUBLE
);